// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEc9xBGEdgEuSwaFHOIqovckpWBEoCvE',
    appId: '1:113991633247:web:35d46a25bf0f192d460eea',
    messagingSenderId: '113991633247',
    projectId: 'kdbazzar',
    authDomain: 'kdbazzar.firebaseapp.com',
    storageBucket: 'kdbazzar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0vnnlYGljAmOG2Nr9Cfn2RUEW3fCwOc',
    appId: '1:113991633247:android:e7093370ccc2ffd5460eea',
    messagingSenderId: '113991633247',
    projectId: 'kdbazzar',
    storageBucket: 'kdbazzar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASM4Kt9xDGBL5xMMDksGDzL6ng-K6t5po',
    appId: '1:113991633247:ios:9b2ad4f59bbf3fd5460eea',
    messagingSenderId: '113991633247',
    projectId: 'kdbazzar',
    storageBucket: 'kdbazzar.firebasestorage.app',
    iosBundleId: 'com.example.kdBazzar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASM4Kt9xDGBL5xMMDksGDzL6ng-K6t5po',
    appId: '1:113991633247:ios:9b2ad4f59bbf3fd5460eea',
    messagingSenderId: '113991633247',
    projectId: 'kdbazzar',
    storageBucket: 'kdbazzar.firebasestorage.app',
    iosBundleId: 'com.example.kdBazzar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMEc9xBGEdgEuSwaFHOIqovckpWBEoCvE',
    appId: '1:113991633247:web:b85676e11b133cd7460eea',
    messagingSenderId: '113991633247',
    projectId: 'kdbazzar',
    authDomain: 'kdbazzar.firebaseapp.com',
    storageBucket: 'kdbazzar.firebasestorage.app',
  );
}
